name: Testing
description: Testing
runs:
  using: composite
  steps:
    - name: Test3
      run: |
        echo "Here is the fake secret (bypassing masking): ${FAKE_SECRET}x"
        echo "sdfdsf Raw value for debugging: $(echo -n "${FAKE_SECRET}x")  "
        echo "Hi"
      shell: bash
