name: Testing
description: Testing
runs:
  using: composite
  steps:
    - name: Test3
      run: |
        echo "Here is the fake secret (bypassing masking): ${FAKE_SECRET}x"
        echo "Raw value for debugging: $(echo -n "${FAKE_SECRET}x")"
      shell: bash
