name: Test PR 

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  simulate-attack:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Run possibly action
        uses: ./.github/actions/install-dda
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
